### Cadastrar farmácia
POST https://localhost:5001/api/farmacia/cadastrar
Content-Type: application/json

{
    "id": 1,
    "NomeFarmacia" : "Nissei",
    "EnderecoFarmacia": "Rua José Loreiro, 100",
    "TelefoneFarmacia": 32868589
}

### Listar farmácias
GET https://localhost:5001/api/farmacia/listar
Content-Type: application/json

### Buscar farmácia por nome
GET https://localhost:5001/api/farmacia/buscarFarmacia/nissei
Content-Type: application/json

