### Cadastrar produto
POST https://localhost:5001/api/produto/cadastrar
Content-Type: application/json

{
    "Id": 8,
    "NomeProduto": "YazFlex",
    "PrecoProduto": 33.5,
    "DescontoProduto": 0,
    "FarmaciaId": 1 ,
    "FormaProdutoId": 1
}

### Listar produtos
GET https://localhost:5001/api/produto/listar
Content-Type: application/json


### Buscar produto por nome
GET https://localhost:5001/api/produto/buscarProduto/YazFlex
Content-Type: application/json

### Atualizar produto
PUT https://localhost:5001/api/produto/atualizarProduto/YazFlex
Content-Type: application/json

{
    "Id": 2,
    "nomeProduto": "YazFlex",
    "precoProduto": 72.90
}

### Deletar produto pelo nome
DELETE https://localhost:5001/api/produto/deletarProduto/YazFlex